### ISSUE TITLE
ReactQueryの導入

### ISSUE THREAD

**Issue by mercy34mercy** [Shunkicreate/busdes-kic-web#22]
# やってほしいこと
ReactQueryを導入してほしい

## 伝言
openapi.yml　あります

# 参考記事
https://zenn.dev/nixieminton/articles/e3a2f48d4e8e34

**Comment by Shunkicreate** [comment]
やります！！！！！！！

**Comment by Shunkicreate** [comment]
いろいろまーしーと健闘した結果
「ハッシュマップの扱いが恐らくopenapiだときつい」という結論に至りました。
今回試してみた結果、
[openapi-codegen](https://github.com/fabien0102/openapi-codegen)
useQueryをそのまま作ってくれるやつ。
[orval](https://orval.dev/guides/react-query)
同じくuseQueryを作ってくれる。そこそこちゃんとしてそう
[openapi-generator](https://github.com/OpenAPITools/openapi-generator)
axiosしかできないが、安定してる。

**Comment by Shunkicreate** [comment]
スキーマ駆動とは趣旨が離れるけど普通にreactQueryを入れる
