### ISSUE TITLE
atomのバスの路線追加ボタンを作る

### ISSUE THREAD

**Issue by Shunkicreate** [Shunkicreate/busdes-kic-web#6]
場所はsrc/atom

**Comment by Kyororillex** [comment]
お部屋環境構築できたからおうちでも研究ができるね☺️☺️☺️☺️

追加ボタンやります！！！

**Comment by Shunkicreate** [comment]
恭平のキーボードっておれと同じやつ？

**Comment by Kyororillex** [comment]
ロジクール K835GPR 有線 メカニカルキーボード 赤軸 リニア テンキーレス コンパクト メカニカル キーボード 有線 有線キーボード グラファイト windows surface K835 国内正規品 https://amzn.asia/d/5C5EvOj

JISやのにソフト入れんとUSになるからmacでWindows用の買う人は初めからUS買った方がいいっぽい。

**Comment by Shunkicreate** [comment]
いっしょや
windowsやと普通に動くわ
勝手にドライバ入れてくれてるんかも
