### ISSUE TITLE
layoutのヘッダー作成

### ISSUE THREAD

**Issue by Shunkicreate** [Shunkicreate/busdes-kic-web#7]
場所は```src/layouts```

**Comment by Kyororillex** [comment]
文字のサイズかんを確認してほしい

![スクリーンショット 2023-03-11 4 00 31](https://user-images.githubusercontent.com/89798115/224403363-3c492a97-d887-49ce-8dbc-2373f77238c4.png)

**Comment by Kyororillex** [comment]
カードのサイズも小さくした方がいいよなーーーー
